version: '3.3'

services:
  some-redis:
    container_name: some-redis
    image: redis
    ports:
      - 6379:6379
  service-2:
    container_name: service-2
    image: service-2
    ports:
      - 8080:8080
    depends_on:
      - some-redis
    environment:
      - SPRING_REDIS_HOST=some-redis
      - SPRING_REDIS_PORT=6379